import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useRef, useState } from 'react';
import io from 'socket.io-client';

const inter = Inter({ subsets: ['latin'] })

const socket = io('http://localhost:4000');

function Chat() {
  const [username, setUsername] = useState('')
  const [messages, setMessages] = useState([]);
  const messageInputRef = useRef();

  useEffect(() => {
    const user = (prompt('Enter your username:'));
    setUsername(user)
    socket.emit('register', user);

    socket.on('connect', () => {
      console.log('Connected to Socket.io server');
    });

    socket.on('disconnect', () => {
      console.log('Disconnected from Socket.io server');
    });

    socket.on('message', data => {
      console.log('Received message:', data);
      setMessages(messages => [...messages, data]);
    });
  }, []);

  function handleSubmit(event) {
    event.preventDefault();
    const text = messageInputRef.current.value.trim();
    if (text) {
      socket.emit('message', { text });
      messageInputRef.current.value = '';
    }
  }

  return (
    <div>
      <ul>
        {messages.map((message, index) => (
          <li key={index}>{message.username}: {message.message.text}</li>
        ))}
      </ul>
      <form onSubmit={handleSubmit}>
        <input ref={messageInputRef} />
        <button type="submit">Send</button>
      </form>
    </div>
  );
}

export default function Home() {

  return (
    <>
      <Head>
        <title>Support Ticket System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
    <Chat />
      </div>
    </>
  )
}
