import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useRef, useState } from 'react';
import io from 'socket.io-client';
import { Tab, Tabs, TextField } from '@mui/material';

const inter = Inter({ subsets: ['latin'] })

const socket = io('http://localhost:4000');

function Chat() {
  const [username, setUsername] = useState('')
  const [messages, setMessages] = useState([]);
  const messageInputRef = useRef();

  useEffect(() => {
    const user = "Hello" || (prompt('Enter your username:'));
    setUsername(user)
    socket.emit('register', user);

    socket.on('connect', () => {
      console.log('Connected to Socket.io server');
    });

    socket.on('disconnect', () => {
      console.log('Disconnected from Socket.io server');
    });

    socket.on('message', data => {
      console.log('Received message:', data);
      setMessages(messages => [...messages, data]);
    });
  }, []);

  function handleSubmit(event) {
    event.preventDefault();
    const text = messageInputRef.current.value.trim();
    if (text) {
      socket.emit('message', { text });
      messageInputRef.current.value = '';
    }
  }

  return (
   

<div className="w-full px-5 flex flex-col justify-between">
<div className="flex flex-col mt-5">
  <div className="flex justify-end mb-4">
    <div
      className="mr-2 py-3 px-4 bg-blue-400 rounded-bl-3xl rounded-tl-3xl rounded-tr-xl text-white"
    >
      Welcome to group everyone !
    </div>
    <img
      src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
      className="object-cover h-8 w-8 rounded-full"
      alt=""
    />
  </div>
  <div className="flex justify-start mb-4">
    <img
      src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
      className="object-cover h-8 w-8 rounded-full"
      alt=""
    />
    <div
      className="ml-2 py-3 px-4 bg-gray-400 rounded-br-3xl rounded-tr-3xl rounded-tl-xl text-white"
    >
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat
      at praesentium, aut ullam delectus odio error sit rem. Architecto
      nulla doloribus laborum illo rem enim dolor odio saepe,
      consequatur quas?
    </div>
  </div>
  <div className="flex justify-end mb-4">
    <div>
      <div
        className="mr-2 py-3 px-4 bg-blue-400 rounded-bl-3xl rounded-tl-3xl rounded-tr-xl text-white"
      >
        Lorem ipsum dolor, sit amet consectetur adipisicing elit.
        Magnam, repudiandae.
      </div>

      <div
        className="mt-4 mr-2 py-3 px-4 bg-blue-400 rounded-bl-3xl rounded-tl-3xl rounded-tr-xl text-white"
      >
        Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Debitis, reiciendis!
      </div>
    </div>
    <img
      src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
      className="object-cover h-8 w-8 rounded-full"
      alt=""
    />
  </div>
  <div className="flex justify-start mb-4">
    <img
      src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
      className="object-cover h-8 w-8 rounded-full"
      alt=""
    />
    <div
      className="ml-2 py-3 px-4 bg-gray-400 rounded-br-3xl rounded-tr-3xl rounded-tl-xl text-white"
    >
      happy holiday guys!
    </div>
  </div>
</div>
<div className="py-2">
  <input
    className="w-full bg-gray-300 py-2 px-3 rounded"
    type="text"
    placeholder="type your message here..."
  />
</div>
</div>
  );
}

export default function Home() {

  return (
    <>
      <Head>
        <title>Support Ticket System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <Chat /> */}
        {/* <div className="container mx-auto shadow-lg rounded-lg">
          <div className="px-5 py-5 flex justify-between items-center bg-white border-b-2">
            <div className="font-semibold text-2xl">GoingChat</div>
            <div className="w-1/2">
              <input
                type="text"
                name=""
                id=""
                placeholder="search IRL"
                className="rounded-2xl bg-gray-100 py-3 px-5 w-full"
              />
            </div>
            <div
              className="h-12 w-12 p-2 bg-yellow-500 rounded-full text-white font-semibold flex items-center justify-center"
            >
              RA
            </div>
          </div>
          <div className="flex flex-row justify-between bg-white">
            <div className="flex flex-col w-2/5 border-r-2 overflow-y-auto">
              <div className="border-b-2 py-4 px-2">
                <input
                  type="text"
                  placeholder="search chatting"
                  className="py-2 px-2 border-2 border-gray-200 rounded-2xl w-full"
                />
              </div>
              <div
                className="flex flex-row py-4 px-2 justify-center items-center border-b-2"
              >
                <div className="w-1/4">
                  <img
                    src="https://source.unsplash.com/_7LbC5J-jw4/600x600"
                    className="object-cover h-12 w-12 rounded-full"
                    alt=""
                  />
                </div>
                <div className="w-full">
                  <div className="text-lg font-semibold">Luis1994</div>
                  <span className="text-gray-500">Pick me at 9:00 Am</span>
                </div>
              </div>
              <div className="flex flex-row py-4 px-2 items-center border-b-2">
                <div className="w-1/4">
                  <img
                    src="https://source.unsplash.com/otT2199XwI8/600x600"
                    className="object-cover h-12 w-12 rounded-full"
                    alt=""
                  />
                </div>
                <div className="w-full">
                  <div className="text-lg font-semibold">Everest Trip 2021</div>
                  <span className="text-gray-500">Hi Sam, Welcome</span>
                </div>
              </div>
              <div
                className="flex flex-row py-4 px-2 items-center border-b-2 border-l-4 border-blue-400"
              >
                <div className="w-1/4">
                  <img
                    src="https://source.unsplash.com/L2cxSuKWbpo/600x600"
                    className="object-cover h-12 w-12 rounded-full"
                    alt=""
                  />
                </div>
                <div className="w-full">
                  <div className="text-lg font-semibold">MERN Stack</div>
                  <span className="text-gray-500">Lusi : Thanks Everyone</span>
                </div>
              </div>
              <div className="flex flex-row py-4 px-2 items-center border-b-2">
                <div className="w-1/4">
                  <img
                    src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
                    className="object-cover h-12 w-12 rounded-full"
                    alt=""
                  />
                </div>
                <div className="w-full">
                  <div className="text-lg font-semibold">Javascript Indonesia</div>
                  <span className="text-gray-500">Evan : some one can fix this</span>
                </div>
              </div>
              <div className="flex flex-row py-4 px-2 items-center border-b-2">
                <div className="w-1/4">
                  <img
                    src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
                    className="object-cover h-12 w-12 rounded-full"
                    alt=""
                  />
                </div>
                <div className="w-full">
                  <div className="text-lg font-semibold">Javascript Indonesia</div>
                  <span className="text-gray-500">Evan : some one can fix this</span>
                </div>
              </div>

              <div className="flex flex-row py-4 px-2 items-center border-b-2">
                <div className="w-1/4">
                  <img
                    src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
                    className="object-cover h-12 w-12 rounded-full"
                    alt=""
                  />
                </div>
                <div className="w-full">
                  <div className="text-lg font-semibold">Javascript Indonesia</div>
                  <span className="text-gray-500">Evan : some one can fix this</span>
                </div>
              </div>
            </div>
            <div className="w-full px-5 flex flex-col justify-between">
              <div className="flex flex-col mt-5">
                <div className="flex justify-end mb-4">
                  <div
                    className="mr-2 py-3 px-4 bg-blue-400 rounded-bl-3xl rounded-tl-3xl rounded-tr-xl text-white"
                  >
                    Welcome to group everyone !
                  </div>
                  <img
                    src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
                    className="object-cover h-8 w-8 rounded-full"
                    alt=""
                  />
                </div>
                <div className="flex justify-start mb-4">
                  <img
                    src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
                    className="object-cover h-8 w-8 rounded-full"
                    alt=""
                  />
                  <div
                    className="ml-2 py-3 px-4 bg-gray-400 rounded-br-3xl rounded-tr-3xl rounded-tl-xl text-white"
                  >
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat
                    at praesentium, aut ullam delectus odio error sit rem. Architecto
                    nulla doloribus laborum illo rem enim dolor odio saepe,
                    consequatur quas?
                  </div>
                </div>
                <div className="flex justify-end mb-4">
                  <div>
                    <div
                      className="mr-2 py-3 px-4 bg-blue-400 rounded-bl-3xl rounded-tl-3xl rounded-tr-xl text-white"
                    >
                      Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                      Magnam, repudiandae.
                    </div>

                    <div
                      className="mt-4 mr-2 py-3 px-4 bg-blue-400 rounded-bl-3xl rounded-tl-3xl rounded-tr-xl text-white"
                    >
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Debitis, reiciendis!
                    </div>
                  </div>
                  <img
                    src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
                    className="object-cover h-8 w-8 rounded-full"
                    alt=""
                  />
                </div>
                <div className="flex justify-start mb-4">
                  <img
                    src="https://source.unsplash.com/vpOeXr5wmR4/600x600"
                    className="object-cover h-8 w-8 rounded-full"
                    alt=""
                  />
                  <div
                    className="ml-2 py-3 px-4 bg-gray-400 rounded-br-3xl rounded-tr-3xl rounded-tl-xl text-white"
                  >
                    happy holiday guys!
                  </div>
                </div>
              </div>
              <div className="py-5">
                <input
                  className="w-full bg-gray-300 py-5 px-3 rounded-xl"
                  type="text"
                  placeholder="type your message here..."
                />
              </div>
            </div>
            <div className="w-2/5 border-l-2 px-5">
              <div className="flex flex-col">
                <div className="font-semibold text-xl py-4">Mern Stack Group</div>
                <img
                  src="https://source.unsplash.com/L2cxSuKWbpo/600x600"
                  className="object-cover rounded-xl h-64"
                  alt=""
                />
                <div className="font-semibold py-4">Created 22 Sep 2021</div>
                <div className="font-light">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt,
                  perspiciatis!
                </div>
              </div>
            </div>
          </div>
        </div> */}

        {/* <div className='bg-black/20 py-5 px-5'>
          <div>
            Logo
          </div>
        </div> */}

        <div className='grid grid-cols-5 h-screen'>
          <div className='col-span-1'>
            <Tabs className='' aria-label="icon label tabs example">
              <Tab label="OPEN" />
              <Tab label="REQUESTS" />
              <Tab label="CLOSED" />
            </Tabs>

            <div className='px-3'>
            <TextField className='w-full' sx={{paddingY: 0}} />
            </div>

            <div className='my-2 space-y-1'>
              <div className='mx-1 px-2 py-1 border-2 bg-red-100 border-dotted rounded h-24'>
                <div>
                <p className='text-lg'>#1d222</p>
                <p className=''>shubhamvscode@gmail.com</p>
                </div>
                <div className='flex justify-between'>
                <p className='text-xl'>Saurabh</p>
                <p className='bg-red-300 w-8 aspect-square grid place-content-center rounded-full '>A</p>
                </div> 
              </div>

              <div className='mx-1 px-2 py-1 border-2 bg-red-100 border-dotted rounded h-24'>
                <div>
                <p className='text-lg'>#4dwe2</p>
                <p className=''>shubhamvscode@gmail.com</p>
                </div>
                <div className='flex justify-between'>
                <p className='text-xl'>Saurabh</p>
                <p className='bg-red-300 w-8 aspect-square grid place-content-center rounded-full '>A</p>
                </div> 
              </div>

              <div className='mx-1 px-2 py-1 border-2 bg-red-100 border-dotted rounded h-24'>
                <div>
                <p className='text-lg'>#sf55s</p>
                <p className=''>shubhamvscode@gmail.com</p>
                </div>
                <div className='flex justify-between'>
                <p className='text-xl'>Saurabh</p>
                <p className='bg-red-300 w-8 aspect-square grid place-content-center rounded-full '>A</p>
                </div> 
              </div>
            </div>
          </div>
          <div className='bg-pink-100 col-span-3 h-screen'>
            <div className='bg-red-200 grid grid-cols-3 px-6 py-4 sticky top-0'>
              <h1 className=''>Saurabh</h1>
              <div className='text-center'>
                Assignment Not Checked
                <span>#1d222</span>
              </div>
              <p className='text-right'>shubhamvscode@gmail.com</p>
            </div>

            <div className='h-(calc(100vh-56px))'>
              <Chat/>
            </div>
          </div>
          <div className='col-span-1'>

          </div>
        </div>

      </div>
    </>
  )
}
